# Generated by Django 3.2.5 on 2021-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuenode',
            name='last_number_in_queue',
            field=models.SmallIntegerField(default=0),
        ),
    ]
